---
title: "Calculating the large-fire size threshold"
output: html_document
---

Testing the Lorenz curve process in R
```{r, message = FALSE}
# import packages
library(sf)
library(tidyverse)
# library(ineq)
library(readxl)
```


```{r, message = FALSE}
## read in data sources
# fire occurrence
fod_gdb <- "C:/Users/Charlie/Desktop/ArcGIS/data/NatFSim/NatFSim2022/fire_occurrence/FPA_FOD_20221014.gdb"
fires <- st_read(dsn = fod_gdb, layer = "Fires", quiet = TRUE)

# pyromes
pyrome_boundaries <- st_read("C:/Users/Charlie/Desktop/ArcGIS/data/WCS_OPM_FY24/0_AnalysisArea/Pyromes/Pyromes_CONUS_20200206.shp", quiet = TRUE) %>% 
  st_make_valid()

# NatFSim2022 large fire table
ref_df_xl <- read_excel("C:/Users/Charlie/Desktop/FSim_IDG/data/National_HistoricalData_min90ac.xlsx", col_names = FALSE)
```

### cleaning and wrangling
```{r}
## exploring data
# check the data types of columns
glimpse(pyrome_boundaries)

# filter for fires between 2006-2020
fires_2006 <- fires %>% 
  filter(FIRE_YEAR > 2005)


## wrangling
# # transpose dataframes
# 
# # extract the row labels to use as column names
# new_colnames <- as.character(ref_df_xl[[1]])
# 
# # transpose all columns but the first (row labels)
# ref_df <- as.data.frame(t(ref_df_xl[, -1]))
# 
# # assign the column names
# colnames(ref_df) <- new_colnames
# 
# # ptional: add PyromeID (from original colnames)
# ref_df <- ref_df %>%
#   mutate(PyromeID = as.integer(rownames(.))) %>%
#   relocate(PyromeID)
```


```{r}
## calculating the large fire size for a single pyrome
# isolate pyrome 17
py17 <- pyrome_boundaries %>% 
  filter(PYROME == 17) %>% 
  st_transform(st_crs(fires))

# spatial subset fires that intersect with the pyrome
py17_fires <- fires[py17, ] %>% 
  select(FIRE_SIZE, FOD_ID)
#py_fires_alt = st_intersection(fires, py17) # st_intersection returns the same result

# quick plot
plot(st_geometry(py17), border = "black", lwd = 2)
plot(st_geometry(py17_fires), 
     col = adjustcolor("red", alpha.f = 0.4), 
     border = NA, add = TRUE)

# calculate cumulative area, fires, and percentages of each
py17_fires <- py17_fires %>% 
  st_drop_geometry() %>% 
  arrange(desc(FIRE_SIZE)) %>% 
  mutate(
    cum_fires = row_number() / n(),
    cum_fires_per = cum_fires * 100,
    cum_area = cumsum(FIRE_SIZE) / sum(FIRE_SIZE),
    cum_area_per = cum_area * 100
  )

# # plot the lorenz curve
# ggplot(py17_fires, aes(x = cum_fires_per, y = cum_area_per)) +
#   geom_line(color = "blue", linewidth = 1.2) +
#   geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray50") +
#   labs(
#     title = "Lorenz Curve of Burned Area by Fire Count",
#     x = "Cumulative % of Fires",
#     y = "Cumulative % of Area Burned"
#   ) +
#   theme_minimal()

# calculate differences vectors (difference of each element with the element before it)
# dx will have no variance because the spacing of each fire will be uniform
dx <- diff(py17_fires$cum_fires_per)
dy <- diff(py17_fires$cum_area_per)

# calculate slope
slope <- dy/dx
py17_fires$slope <- c(NA, slope)

# find where slope is closest to 1 and extract just the fire size
# finds the index of the row with the smallest absolute value of slope - 1
py17_fires[which.min(abs(py17_fires$slope - 1)), ]
```

### Turning it into a function
```{r}
# function to input any pyrome number
find_min_fire_row <- function(pyrome){
  
  # select pyrome
  py <- pyrome_boundaries %>% 
  filter(PYROME == pyrome) %>% 
  st_transform(st_crs(fires_2006))
  
  # spatial subset fires that intersect with the pyrome
  py_fires <- fires_2006[py, ] %>% 
  select(FIRE_SIZE, FOD_ID)
  
  # calculate cumulative area, fires, and percentages of each
  py_fires <- py_fires %>%
    st_drop_geometry() %>%
    arrange(desc(FIRE_SIZE)) %>%
    mutate(
      cum_fires = row_number() / n(),
      cum_fires_per = cum_fires * 100,
      cum_area = cumsum(FIRE_SIZE) / sum(FIRE_SIZE),
      cum_area_per = cum_area * 100
    )
  
  # calculate differences vectors (difference of each element with the element before it)
  # dx will have no variance because the spacing of each fire will be uniform
  dx <- diff(py_fires$cum_fires_per)
  dy <- diff(py_fires$cum_area_per)
  
  # calculate slope
  slope <- dy / dx
  py_fires$slope <- c(NA, slope)
  
  # find where slope is closest to 1 and extract just the fire size
  # finds the index of the row with the smallest absolute value of slope - 1
  row <- py_fires[which.min(abs(py_fires$slope - 1)), ]
  
  # append the pyrome id
  row$pyrome <- pyrome
  return(row)
  
}
```

### Looping through all pyromes and calculating the minimum fire size
```{r}
# unique pyrome IDs
# pyrome_ids <- unique(pyrome_boundaries$PYROME)
pyrome_ids <- seq(1:10)

# apply the function to all pyromes
rows <- lapply(pyrome_ids, function(id) {
  
  # wrap in tryCatch for error handling
  tryCatch(
    find_min_fire_row(id),
    error = function(e) {
      message(paste("Failed on pyrome", id, ":", e$message))
      return(NULL)
    }
  )
})

# # combine into a dataframe
# fire_thresholds_df <- do.call(rbind, rows) %>% 
#   relocate(pyrome) %>% 
#   select(-(FOD_ID))

# combine into a dataframe
fire_thresholds_df_2006 <- do.call(rbind, rows) %>%
  relocate(pyrome) %>%
  select(-(FOD_ID))
```

The final result we extract for each pyrome is the fire size. This is a threshold above which fires are considered "large fires". The percentage of cumulative fires and cumulative area can be interpreted as 